services:
    _defaults:
        public: false

    Creativestyle\Bundle\AkeneoBundle\Command\CleanupCommand:
        arguments:
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: console.command }
