services:
  oro_akeneo.integration.channel:
    class: Creativestyle\Bundle\AkeneoBundle\Integration\AkeneoChannel
    public: true
    tags:
      - { name: oro_integration.channel, type: oro_akeneo }

  oro_akeneo.integration.transport:
    class: Creativestyle\Bundle\AkeneoBundle\Integration\AkeneoTransport
    arguments:
      - '@oro_akeneo.connection.client_factory'
      - '@oro_currency.config.currency'
      - '@oro_akeneo.integration.search_builder'
      - '@oro_akeneo.importexport.file_manager_writable'
      - '@logger'
    public: true
    tags:
      - { name: oro_integration.transport, channel_type: oro_akeneo, type: oro_akeneo }
